### ISSUE TITLE
Doesn't work on <iframe> embedded videos (e.g. embedded Vimeo)

### ISSUE THREAD

**Issue by mansuen** [WofWca/jumpcutter#13]
Recently, jumpcutter stopped working on Vimeo videos.

**Comment by WofWca** [comment]
Thanks for reporting.
I might have overlooked something, works for me.

If you're just looking for a quick fix, try going to the options page (click the gear button in the popup), then clicking "Reset to defaults".

If you also want to help me debug this, BEFORE resetting to defaults
1. Go to the options page (click the gear icon in the popup).
2. Right click any element
3. Press "Inspect"
4. In the newly open window, open the "Console" tab and paste this:
```js
let local = new Promise(r => chrome.storage.local.get(r));
let sync = new Promise(r => chrome.storage.sync.get(r));
Promise.all([local, sync]).then(res => {
    console.log(JSON.stringify(res, undefined, '  '));
});
```
This will print your current extension settings in raw form.

5. Post them here or email me (wofwca@protonmail.com).

**Comment by WofWca** [comment]
The problem is with <iframe> embedded videos.
I'm planning on fixing this most probably within two weeks.

As a workaround, you can try to
1. Right click the video.
2. Press "View frame source"
3. Iframe URL will appear in your address bar.
4. Copy the part after `view-source:` and paste it on a new tab.
