### ISSUE TITLE
Superb UI, but some sort of processing error

### ISSUE THREAD

**Issue by CodeOptimist** [WofWca/jumpcutter#24]
Edit: Working okay so far today. Apparently you can't easily delete issues so I'll leave this for a day or two and close if I can't repro again today.

Edit 2: I was running into https://github.com/WofWca/jumpcutter/issues/25 repeatedly last night and maybe it was confusing everything.

This is a vague not-particularly-useful issue report, but on Chrome I've been comparing Jump Cutter to Skip Silence, and I much prefer the UI of Jump Cutter. It's the one I _want_ to work.

However, even after adjusting every setting, e.g. setting a 0.5s "margin before" (the distortion & delay don't bother me much), and a decent "margin after" of 0.25s, there is some sort of audio error that still occurs repeatedly. Essentially every 1-3 minutes I won't be able to make sense of what I just heard due to choppiness in their voice. I will jump back and re-play it, and it will play perfectly the second time.

Perhaps it is switching too fast? Too many times in a short period? Seems to happen no matter my margin settings, large or 0.
I thought I was stuck with this until I tried Skip Silence, and it doesn't have this issue, seems to playback perfectly. Perhaps because of its "Sample Threshold" setting? It seems like "margin" is perhaps the equivalent of that in Jump Cutter, but as mentioned something doesn't quite work.

Anyway, love the extension, I much prefer your volume graph and threshold setting - the way the graph scales, it's awesome. But currently have to use Skip Silence instead because of this issue. (After testing each on a few hours of video last night.)

Will see if I can gather more useful information, switching back to Jump Cutter to try to find some helpful repro's.

**Comment by WofWca** [comment]
I think I've noticed it a couple of times too, I believe it has to do with performance drops, `AudioWorkletProcessor` can't keep up with incoming audio data. This even can happen when "Volume threshold" = 0 and "margin before" = 0.
Don't think there is a direct way to solve this.
Maybe for "margin before" = 0 we could use `el.captureStream()` in order to not redirect the audio to the audio processing graph at all.
Or maybe in the future, when the cloning algorithm can be used by default.

**Comment by WofWca** [comment]
I wouldn't say they're fundamentally different, it's just that Skip Silence 4 doesn't have "Margin before" currently, only "Margin after" (because achieving "Margin before" is more complex than "Margin after"). In my extension only "Margin before" is supposed to cause distortion (and only on the "margin before" parts), so try setting it to 0. Also try the "experimental algorithm".
I believe in Skip Silence a "sample" is 0.025 of a second (https://github.com/vantezzen/skip-silence/blob/7b4b1fe0ea8d6e75cab96ab82b9a5c6a41009248/src/pages/content/lib/SilenceSkipper.ts#L338), so "50 samples" is 1.25 seconds. If you want this in my extension, you can adjust the max value of the "margin after" input in options.

**Comment by CodeOptimist** [comment]
From what I can tell, it does have margin before, there is definitely a slower-speed pause before every spoken word when I use it. 🤔

**Comment by CodeOptimist** [comment]
Now that I'm trying JC again, I can say this no longer appears to be happening, you may be right about it being performance related.

By the way, now that this issue is gone for me, and I recently discovered settings #32 and saw it has a "Enable audio-video desynchronization correction" (I didn't know it did this!!! thought that was exclusive to SkipSilence) it's actually playing perfectly smooth, whereas SS stutters each time it resyncs. Your resync is either less frequent or perhaps more cleverly implemented/timed? Nice!
